services:
  db:
    container_name: thesis-db
    restart: always
    env_file: .env
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - thesis-data:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT}:5432"
volumes:
  thesis-data: